/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LearningStyleRouteImport } from './routes/learning-style'
import { Route as DeepAssessmentRouteImport } from './routes/deep-assessment'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ReportCodeRouteImport } from './routes/report.$code'

const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningStyleRoute = LearningStyleRouteImport.update({
  id: '/learning-style',
  path: '/learning-style',
  getParentRoute: () => rootRouteImport,
} as any)
const DeepAssessmentRoute = DeepAssessmentRouteImport.update({
  id: '/deep-assessment',
  path: '/deep-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCodeRoute = ReportCodeRouteImport.update({
  id: '/report/$code',
  path: '/report/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/booking': typeof BookingRoute
  '/deep-assessment': typeof DeepAssessmentRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRoute
  '/report/$code': typeof ReportCodeRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/booking': typeof BookingRoute
  '/deep-assessment': typeof DeepAssessmentRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRoute
  '/report/$code': typeof ReportCodeRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/assessments': typeof AssessmentsRoute
  '/booking': typeof BookingRoute
  '/deep-assessment': typeof DeepAssessmentRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRoute
  '/report/$code': typeof ReportCodeRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assessments'
    | '/booking'
    | '/deep-assessment'
    | '/learning-style'
    | '/resources'
    | '/report/$code'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/assessments'
    | '/booking'
    | '/deep-assessment'
    | '/learning-style'
    | '/resources'
    | '/report/$code'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/assessments'
    | '/booking'
    | '/deep-assessment'
    | '/learning-style'
    | '/resources'
    | '/report/$code'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AssessmentsRoute: typeof AssessmentsRoute
  BookingRoute: typeof BookingRoute
  DeepAssessmentRoute: typeof DeepAssessmentRoute
  LearningStyleRoute: typeof LearningStyleRoute
  ResourcesRoute: typeof ResourcesRoute
  ReportCodeRoute: typeof ReportCodeRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-style': {
      id: '/learning-style'
      path: '/learning-style'
      fullPath: '/learning-style'
      preLoaderRoute: typeof LearningStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deep-assessment': {
      id: '/deep-assessment'
      path: '/deep-assessment'
      fullPath: '/deep-assessment'
      preLoaderRoute: typeof DeepAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$code': {
      id: '/report/$code'
      path: '/report/$code'
      fullPath: '/report/$code'
      preLoaderRoute: typeof ReportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AssessmentsRoute: AssessmentsRoute,
  BookingRoute: BookingRoute,
  DeepAssessmentRoute: DeepAssessmentRoute,
  LearningStyleRoute: LearningStyleRoute,
  ResourcesRoute: ResourcesRoute,
  ReportCodeRoute: ReportCodeRoute,
  ReportIndexRoute: ReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
