/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfDiscoveryRouteImport } from './routes/self-discovery'
import { Route as SectorGuideRouteImport } from './routes/sector-guide'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as LearningStyleRouteImport } from './routes/learning-style'
import { Route as LaborMarketRouteImport } from './routes/labor-market'
import { Route as JoinAsCoachRouteImport } from './routes/join-as-coach'
import { Route as CounselorRouteImport } from './routes/counselor'
import { Route as ComprehensiveAssessmentRouteImport } from './routes/comprehensive-assessment'
import { Route as CareerTypeAssessmentRouteImport } from './routes/career-type-assessment'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AcademicMajorRouteImport } from './routes/academic-major'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIndexRouteImport } from './routes/report.index'
import { Route as ResourcesCoachingVsCareerCounselingRouteImport } from './routes/resources.coaching-vs-career-counseling'
import { Route as ResourcesCareerPathTermsRouteImport } from './routes/resources.career-path-terms'
import { Route as ReportCodeRouteImport } from './routes/report.$code'

const SelfDiscoveryRoute = SelfDiscoveryRouteImport.update({
  id: '/self-discovery',
  path: '/self-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorGuideRoute = SectorGuideRouteImport.update({
  id: '/sector-guide',
  path: '/sector-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningStyleRoute = LearningStyleRouteImport.update({
  id: '/learning-style',
  path: '/learning-style',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborMarketRoute = LaborMarketRouteImport.update({
  id: '/labor-market',
  path: '/labor-market',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinAsCoachRoute = JoinAsCoachRouteImport.update({
  id: '/join-as-coach',
  path: '/join-as-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselorRoute = CounselorRouteImport.update({
  id: '/counselor',
  path: '/counselor',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprehensiveAssessmentRoute = ComprehensiveAssessmentRouteImport.update({
  id: '/comprehensive-assessment',
  path: '/comprehensive-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerTypeAssessmentRoute = CareerTypeAssessmentRouteImport.update({
  id: '/career-type-assessment',
  path: '/career-type-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicMajorRoute = AcademicMajorRouteImport.update({
  id: '/academic-major',
  path: '/academic-major',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCoachingVsCareerCounselingRoute =
  ResourcesCoachingVsCareerCounselingRouteImport.update({
    id: '/coaching-vs-career-counseling',
    path: '/coaching-vs-career-counseling',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ResourcesCareerPathTermsRoute =
  ResourcesCareerPathTermsRouteImport.update({
    id: '/career-path-terms',
    path: '/career-path-terms',
    getParentRoute: () => ResourcesRoute,
  } as any)
const ReportCodeRoute = ReportCodeRouteImport.update({
  id: '/report/$code',
  path: '/report/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-major': typeof AcademicMajorRoute
  '/booking': typeof BookingRoute
  '/career-type-assessment': typeof CareerTypeAssessmentRoute
  '/comprehensive-assessment': typeof ComprehensiveAssessmentRoute
  '/counselor': typeof CounselorRoute
  '/join-as-coach': typeof JoinAsCoachRoute
  '/labor-market': typeof LaborMarketRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sector-guide': typeof SectorGuideRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/report/$code': typeof ReportCodeRoute
  '/resources/career-path-terms': typeof ResourcesCareerPathTermsRoute
  '/resources/coaching-vs-career-counseling': typeof ResourcesCoachingVsCareerCounselingRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-major': typeof AcademicMajorRoute
  '/booking': typeof BookingRoute
  '/career-type-assessment': typeof CareerTypeAssessmentRoute
  '/comprehensive-assessment': typeof ComprehensiveAssessmentRoute
  '/counselor': typeof CounselorRoute
  '/join-as-coach': typeof JoinAsCoachRoute
  '/labor-market': typeof LaborMarketRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sector-guide': typeof SectorGuideRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/report/$code': typeof ReportCodeRoute
  '/resources/career-path-terms': typeof ResourcesCareerPathTermsRoute
  '/resources/coaching-vs-career-counseling': typeof ResourcesCoachingVsCareerCounselingRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-major': typeof AcademicMajorRoute
  '/booking': typeof BookingRoute
  '/career-type-assessment': typeof CareerTypeAssessmentRoute
  '/comprehensive-assessment': typeof ComprehensiveAssessmentRoute
  '/counselor': typeof CounselorRoute
  '/join-as-coach': typeof JoinAsCoachRoute
  '/labor-market': typeof LaborMarketRoute
  '/learning-style': typeof LearningStyleRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/sector-guide': typeof SectorGuideRoute
  '/self-discovery': typeof SelfDiscoveryRoute
  '/report/$code': typeof ReportCodeRoute
  '/resources/career-path-terms': typeof ResourcesCareerPathTermsRoute
  '/resources/coaching-vs-career-counseling': typeof ResourcesCoachingVsCareerCounselingRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-major'
    | '/booking'
    | '/career-type-assessment'
    | '/comprehensive-assessment'
    | '/counselor'
    | '/join-as-coach'
    | '/labor-market'
    | '/learning-style'
    | '/resources'
    | '/sector-guide'
    | '/self-discovery'
    | '/report/$code'
    | '/resources/career-path-terms'
    | '/resources/coaching-vs-career-counseling'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-major'
    | '/booking'
    | '/career-type-assessment'
    | '/comprehensive-assessment'
    | '/counselor'
    | '/join-as-coach'
    | '/labor-market'
    | '/learning-style'
    | '/resources'
    | '/sector-guide'
    | '/self-discovery'
    | '/report/$code'
    | '/resources/career-path-terms'
    | '/resources/coaching-vs-career-counseling'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-major'
    | '/booking'
    | '/career-type-assessment'
    | '/comprehensive-assessment'
    | '/counselor'
    | '/join-as-coach'
    | '/labor-market'
    | '/learning-style'
    | '/resources'
    | '/sector-guide'
    | '/self-discovery'
    | '/report/$code'
    | '/resources/career-path-terms'
    | '/resources/coaching-vs-career-counseling'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicMajorRoute: typeof AcademicMajorRoute
  BookingRoute: typeof BookingRoute
  CareerTypeAssessmentRoute: typeof CareerTypeAssessmentRoute
  ComprehensiveAssessmentRoute: typeof ComprehensiveAssessmentRoute
  CounselorRoute: typeof CounselorRoute
  JoinAsCoachRoute: typeof JoinAsCoachRoute
  LaborMarketRoute: typeof LaborMarketRoute
  LearningStyleRoute: typeof LearningStyleRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SectorGuideRoute: typeof SectorGuideRoute
  SelfDiscoveryRoute: typeof SelfDiscoveryRoute
  ReportCodeRoute: typeof ReportCodeRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-discovery': {
      id: '/self-discovery'
      path: '/self-discovery'
      fullPath: '/self-discovery'
      preLoaderRoute: typeof SelfDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sector-guide': {
      id: '/sector-guide'
      path: '/sector-guide'
      fullPath: '/sector-guide'
      preLoaderRoute: typeof SectorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-style': {
      id: '/learning-style'
      path: '/learning-style'
      fullPath: '/learning-style'
      preLoaderRoute: typeof LearningStyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor-market': {
      id: '/labor-market'
      path: '/labor-market'
      fullPath: '/labor-market'
      preLoaderRoute: typeof LaborMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-as-coach': {
      id: '/join-as-coach'
      path: '/join-as-coach'
      fullPath: '/join-as-coach'
      preLoaderRoute: typeof JoinAsCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counselor': {
      id: '/counselor'
      path: '/counselor'
      fullPath: '/counselor'
      preLoaderRoute: typeof CounselorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprehensive-assessment': {
      id: '/comprehensive-assessment'
      path: '/comprehensive-assessment'
      fullPath: '/comprehensive-assessment'
      preLoaderRoute: typeof ComprehensiveAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-type-assessment': {
      id: '/career-type-assessment'
      path: '/career-type-assessment'
      fullPath: '/career-type-assessment'
      preLoaderRoute: typeof CareerTypeAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-major': {
      id: '/academic-major'
      path: '/academic-major'
      fullPath: '/academic-major'
      preLoaderRoute: typeof AcademicMajorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/coaching-vs-career-counseling': {
      id: '/resources/coaching-vs-career-counseling'
      path: '/coaching-vs-career-counseling'
      fullPath: '/resources/coaching-vs-career-counseling'
      preLoaderRoute: typeof ResourcesCoachingVsCareerCounselingRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/resources/career-path-terms': {
      id: '/resources/career-path-terms'
      path: '/career-path-terms'
      fullPath: '/resources/career-path-terms'
      preLoaderRoute: typeof ResourcesCareerPathTermsRouteImport
      parentRoute: typeof ResourcesRoute
    }
    '/report/$code': {
      id: '/report/$code'
      path: '/report/$code'
      fullPath: '/report/$code'
      preLoaderRoute: typeof ReportCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResourcesRouteChildren {
  ResourcesCareerPathTermsRoute: typeof ResourcesCareerPathTermsRoute
  ResourcesCoachingVsCareerCounselingRoute: typeof ResourcesCoachingVsCareerCounselingRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesCareerPathTermsRoute: ResourcesCareerPathTermsRoute,
  ResourcesCoachingVsCareerCounselingRoute:
    ResourcesCoachingVsCareerCounselingRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicMajorRoute: AcademicMajorRoute,
  BookingRoute: BookingRoute,
  CareerTypeAssessmentRoute: CareerTypeAssessmentRoute,
  ComprehensiveAssessmentRoute: ComprehensiveAssessmentRoute,
  CounselorRoute: CounselorRoute,
  JoinAsCoachRoute: JoinAsCoachRoute,
  LaborMarketRoute: LaborMarketRoute,
  LearningStyleRoute: LearningStyleRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SectorGuideRoute: SectorGuideRoute,
  SelfDiscoveryRoute: SelfDiscoveryRoute,
  ReportCodeRoute: ReportCodeRoute,
  ReportIndexRoute: ReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
